dist: trusty
language: scala
scala:
  - 2.12.10
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -U postgres -c "CREATE USER enricher WITH password 'supersecret1';"
  - psql -U postgres -c "CREATE DATABASE sql_enrichment_test WITH OWNER = enricher;"
  - psql -U postgres -d sql_enrichment_test < integration-tests/sql-enrichment-test.sql
  - psql -U postgres -d sql_enrichment_test -c "GRANT ALL ON enrichment_test TO enricher;"
script:
  - python integration-tests/api-lookup-test.py &
  - sbt test
deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: l7sf6itOPMU4/5ZLBJLmXD3sC7+9aUztVN0DXlwSURkd+nzse9DzZnHr2mrRoNIkdQl7VzvG9wqVVx7RKVtg5zl+zpTRHPllbIvsY9x3feg36QlaqvGnk/6jKASEIrneGwIhXO4cYLl47I+CZNW/yMdU3N8W2OR2QRuVRQ8MW4h9Dql4hVxoRQsrb8f4GP7wo+F6ElLsJcxbEgugMXF7eBMNjBZOCGl1C39fPr1riIH53h8qsHZ6x6dg6mkMZT0/vsGpGGVZCGXk9Ovg0qPPgxJEg1wB8rgeIsxoUa0V1B0iW+wl0YzSuDY3Ad0BERe64vjwP1IayXH1bUS+fE3aSSkU64v+BCDQ9rY1cg87TLDiMSOCNWfBcuVcJG8iYKos7LmcyEPkF/FjO3IO1CTddqGTtreqJ5zvF9muFONHHAsXNsi6WQt67lJD6GbbT/85TOnTy1N0cIkrrJrqMAmGX9NnJ186m3RcK9h+UGb2ZjoVT4j5Xn/he3cN56OetI9JjGnbzAe6ypcoPR1S065en848BT1uVX/hQQ4oLwkK/42MUFZMllxrQ5m0jka9+9mwBuBecgLpdZHs6PoDVVDvK65iwxD9GXYRROYfYAgdtuLoPf1D1HicKVfMGsvHENdS6p2y8/ybJrBPjQSJOpxeD6Gv+0s08PJdeBIOvrDkEW4=
  - secure: pxdGaFwFr3JE7lweNsq3vlB1wtatGElSq2iCX8oY9pnky2LfRjyC5ING+90xuvOcJ+CSvXcolClnw8XuwMBrO6iWbBh0zRFUVB3QtvHisJqaEneqyHyOuJU7nfNRzbsunydwFzcDPzan3vAnddXY1yeM0rZI72ntOEJQtEeH1KEW8Ttmj4faM9kogAWp1TYRm6R2ldjqXd6vIWTY4+AnGAfOXWeKhiGi9q488psYR6FB3zGltTBah9joo5iWgEMGkGZakQd5k6dcO5IPIm3tuyvXtPt/GYdBUDM8PKzc9y02kWhEF+eqXFknmBk4mzQwzdG8auM9eOduBuZgmQN2pWxl3YvMmhJzWIRhzra1QDFdAP8nAWGgfEOge50pU1Wh5j0sFuEWUe+7gR507mMaztka57zoUsC2tXIh2+obAziSRF5T3MzVbq4rlVuBf2riR/j2xn3vESkc9ucapJx8MTDZJkbnt8GV+edusalXI1RIWk/KnPEM6aTYZTWTbhLo3AONCBPQSmIBaIRfFCkDiC9vXzaKi+MiA/iDCYm88sCUjyW4z5X7PVO/7e0PE+ZYjfaf1yX0JUqg9H2nzRQNkqCafVaL7obzbZ8u/wvjr+aG6PIl2JElhmoO3omImx53ocWHa5D7mqwij4siX4GBHZVUjnOzES/jDMEcxOzlGZA=
